"""
Phase 10 validation — chart_tools, report_agent, pdf_builder.
Run with: pytest tests/test_phase10.py -v
"""
import sys
import os
import base64
import tempfile
import pytest
from pathlib import Path
from unittest.mock import MagicMock

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

SAMPLE_CSV = Path(__file__).resolve().parent.parent / "sample_data" / "hde_overland_sales_2022_2024.csv"


# -----------------------------------------------------------------------------
# chart_tools tests
# -----------------------------------------------------------------------------

@pytest.fixture
def clean_df():
    from tools.data_tools import load_dataframe, clean_dataframe
    return clean_dataframe(load_dataframe(SAMPLE_CSV))


def test_revenue_by_year_chart_returns_base64(clean_df):
    from tools.chart_tools import revenue_by_year_chart
    result = revenue_by_year_chart(clean_df)
    assert isinstance(result, str)
    assert len(result) > 100
    # Verify it's valid base64 PNG
    decoded = base64.b64decode(result)
    assert decoded[:4] == b'\x89PNG'


def test_revenue_by_build_category_chart_returns_base64(clean_df):
    from tools.chart_tools import revenue_by_build_category_chart
    result = revenue_by_build_category_chart(clean_df)
    assert isinstance(result, str)
    assert len(result) > 100


def test_baja_growth_trend_chart_returns_base64(clean_df):
    from tools.chart_tools import baja_growth_trend_chart
    result = baja_growth_trend_chart(clean_df)
    assert isinstance(result, str)
    assert len(result) > 100


def test_revenue_by_region_chart_returns_base64(clean_df):
    from tools.chart_tools import revenue_by_region_chart
    result = revenue_by_region_chart(clean_df)
    assert isinstance(result, str)
    assert len(result) > 100


def test_generate_all_charts_returns_four_keys(clean_df):
    from tools.chart_tools import generate_all_charts
    charts = generate_all_charts(clean_df)
    assert set(charts.keys()) == {
        "revenue_by_year",
        "revenue_by_build_category",
        "baja_growth_trend",
        "revenue_by_region",
    }
    assert all(isinstance(v, str) for v in charts.values())


def test_chart_returns_empty_string_on_missing_columns():
    from tools.chart_tools import revenue_by_year_chart
    import pandas as pd
    empty_df = pd.DataFrame({"a": [1, 2], "b": [3, 4]})
    result = revenue_by_year_chart(empty_df)
    assert result == ""


# -----------------------------------------------------------------------------
# report_agent tests
# -----------------------------------------------------------------------------

REPORT_STATE = {
    "business_question": "Is the Baja segment growing fast enough to justify dedicated product lines?",
    "executive_summary": "Baja is growing. Act now.",
    "data_findings": ["Baja grew 64% YoY", "Southwest dominates"],
    "market_findings": ["Market grew 22%", "No dedicated line exists"],
    "recommendations": [
        {"rank": 1, "action": "Launch Baja line", "rationale": "64% growth",
         "priority": "high", "timeframe": "short_term"},
    ],
    "opportunities": ["Pre-runner gear gap"],
    "data_health_score": 91,
    "errors": [],
}

SAMPLE_REPORT = """# Baja Intelligence Report

## Executive Summary
Baja is growing fast. HDE should act immediately.

## Data Findings
- Baja grew 64% year-over-year

## Strategic Recommendations
1. **Launch dedicated Baja product line** [HIGH / short term]
   Revenue growth justifies the investment.

---
*Report generated by Overland Intelligence System v1.0*"""


def make_report_llm(content=SAMPLE_REPORT):
    mock = MagicMock()
    mock.invoke.return_value = MagicMock(content=content)
    return mock


def test_report_agent_returns_markdown():
    from agents.report_agent import run_report_agent
    result = run_report_agent(dict(REPORT_STATE), make_report_llm())
    assert "report_markdown" in result
    assert len(result["report_markdown"]) > 50


def test_report_agent_status_set():
    from agents.report_agent import run_report_agent
    result = run_report_agent(dict(REPORT_STATE), make_report_llm())
    assert result["status"] == "report_complete"


def test_report_agent_strips_code_fences():
    from agents.report_agent import run_report_agent
    fenced = f"```markdown\n{SAMPLE_REPORT}\n```"
    result = run_report_agent(dict(REPORT_STATE), make_report_llm(fenced))
    assert not result["report_markdown"].startswith("```")


def test_report_agent_raises_on_llm_failure():
    from agents.report_agent import run_report_agent
    from tools.exceptions import LLMProviderError
    bad_llm = MagicMock()
    bad_llm.invoke.side_effect = Exception("LLM offline")
    with pytest.raises(LLMProviderError):
        run_report_agent(dict(REPORT_STATE), bad_llm)


# -----------------------------------------------------------------------------
# pdf_builder tests
# -----------------------------------------------------------------------------

def test_pdf_builder_creates_file():
    from output.pdf_builder import build_pdf
    with tempfile.TemporaryDirectory() as tmpdir:
        path = os.path.join(tmpdir, "test_report.pdf")
        result = build_pdf(SAMPLE_REPORT, {}, output_path=path)
        assert os.path.exists(result)
        assert os.path.getsize(result) > 1000


def test_pdf_builder_with_charts():
    from output.pdf_builder import build_pdf
    from tools.data_tools import load_dataframe, clean_dataframe
    from tools.chart_tools import generate_all_charts
    df = clean_dataframe(load_dataframe(SAMPLE_CSV))
    charts = generate_all_charts(df)
    with tempfile.TemporaryDirectory() as tmpdir:
        path = os.path.join(tmpdir, "full_report.pdf")
        result = build_pdf(SAMPLE_REPORT, charts, output_path=path)
        assert os.path.exists(result)
        assert os.path.getsize(result) > 5000


def test_pdf_builder_returns_path_string():
    from output.pdf_builder import build_pdf
    with tempfile.TemporaryDirectory() as tmpdir:
        path = os.path.join(tmpdir, "out.pdf")
        result = build_pdf(SAMPLE_REPORT, {}, output_path=path)
        assert isinstance(result, str)
        assert result.endswith(".pdf")


def test_markdown_to_html_converts_headers():
    from output.pdf_builder import _markdown_to_html
    md = "# Title\n## Section\n### Subsection"
    html = _markdown_to_html(md)
    assert "<h1>" in html
    assert "<h2>" in html
    assert "<h3>" in html


def test_markdown_to_html_converts_bullets():
    from output.pdf_builder import _markdown_to_html
    md = "- Item one\n- Item two\n- Item three"
    html = _markdown_to_html(md)
    assert "<ul>" in html
    assert "<li>" in html
    assert html.count("<li>") == 3